# Generated by Django 3.1.2 on 2020-10-27 11:46

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0002_delete_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_location', models.CharField(max_length=255)),
                ('to_location', models.CharField(max_length=255)),
                ('pickup_location', models.CharField(max_length=255)),
                ('dropoff_location', models.CharField(max_length=255)),
                ('plate_number', models.CharField(blank=True, max_length=100, null=True)),
                ('package_size', models.CharField(blank=True, max_length=100, null=True)),
                ('current_mileage', models.CharField(blank=True, max_length=100, null=True)),
                ('year_of_manufacture', models.PositiveBigIntegerField(blank=True, null=True)),
                ('package_description', models.TextField(blank=True, null=True)),
                ('company_name_sender', models.CharField(blank=True, max_length=255, null=True)),
                ('sender_name', models.CharField(max_length=255)),
                ('sender_email', models.CharField(blank=True, max_length=255, null=True)),
                ('sender_mobile_number', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('company_name_receiver', models.CharField(blank=True, max_length=255, null=True)),
                ('receiver_name', models.CharField(max_length=255)),
                ('total_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('transaction_id_total_payment', models.CharField(blank=True, max_length=255, null=True)),
                ('initial_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('transaction_id_initial_payment', models.CharField(blank=True, max_length=255, null=True)),
                ('final_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('transaction_id_final_payment', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_mode', models.CharField(blank=True, max_length=100, null=True)),
                ('date_ordered', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_order', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
